version: '3.1'
services:
  frontend:
    container_name: frontend_services
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend_services
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    restart: always
    volumes:
      - versions_persistent:/app/alembic/versions
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: db_restaurant
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DB}
    ports:
      - "${SQL_PORT_OUT}:5432"
    restart: always
    volumes:
      - db_restaurant:/var/lib/postgresql/data

volumes:
  db_restaurant:
  versions_persistent: