"""empty message

Revision ID: 01686e581b50
Revises: 6b5654e65a10
Create Date: 2024-02-06 21:46:07.801980

"""
from alembic import op
import sqlalchemy as sa
import fastapi_utils


# revision identifiers, used by Alembic.
revision = '01686e581b50'
down_revision = '6b5654e65a10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'food_log', ['id'])
    op.create_unique_constraint(None, 'food_transactions', ['id'])
    op.add_column('ms_food', sa.Column('description', sa.String(length=256), nullable=False))
    op.add_column('ms_food', sa.Column('status', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'ms_food', ['id'])
    op.create_unique_constraint(None, 'ms_food_category', ['id'])
    op.create_unique_constraint(None, 'ms_restaurant', ['id'])
    op.create_unique_constraint(None, 'ms_role', ['id'])
    op.create_unique_constraint(None, 'ms_user', ['id'])
    op.create_unique_constraint(None, 'order_and_payments', ['id'])
    op.create_unique_constraint(None, 'payment_acceptance_log', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_acceptance_log', type_='unique')
    op.drop_constraint(None, 'order_and_payments', type_='unique')
    op.drop_constraint(None, 'ms_user', type_='unique')
    op.drop_constraint(None, 'ms_role', type_='unique')
    op.drop_constraint(None, 'ms_restaurant', type_='unique')
    op.drop_constraint(None, 'ms_food_category', type_='unique')
    op.drop_constraint(None, 'ms_food', type_='unique')
    op.drop_column('ms_food', 'status')
    op.drop_column('ms_food', 'description')
    op.drop_constraint(None, 'food_transactions', type_='unique')
    op.drop_constraint(None, 'food_log', type_='unique')
    # ### end Alembic commands ###
