"""empty message

Revision ID: 176061424bab
Revises: 01686e581b50
Create Date: 2024-02-06 22:14:12.763207

"""
from alembic import op
import sqlalchemy as sa
import fastapi_utils


# revision identifiers, used by Alembic.
revision = '176061424bab'
down_revision = '01686e581b50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_transactions', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_transactions', 'total_price')
    # ### end Alembic commands ###
