"""empty message

Revision ID: bd8f516ec41f
Revises: 176061424bab
Create Date: 2024-02-07 06:34:15.949900

"""
from alembic import op
import sqlalchemy as sa
import fastapi_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd8f516ec41f'
down_revision = '176061424bab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('food_transactions_user_id_fkey', 'food_transactions', type_='foreignkey')
    op.drop_column('food_transactions', 'user_id')
    op.add_column('order_and_payments', sa.Column('user_id', fastapi_utils.guid_type.GUID(), nullable=True))
    op.create_foreign_key(None, 'order_and_payments', 'ms_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_and_payments', type_='foreignkey')
    op.drop_column('order_and_payments', 'user_id')
    op.add_column('food_transactions', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('food_transactions_user_id_fkey', 'food_transactions', 'ms_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
